name: Build

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  CPP:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set-up
        run: |
            choco install mingw

      - name: Build with g++
        run: |
            g++ -static "Quick Python File Creater.cpp" -o "Quick Python File Creater.exe" 

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: C++ - Quick Python File Creater
          path: |
            Quick Python File Creater.exe
  Python:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set-up
        shell: cmd
        run: |
            pip install pyinstaller
            python "Get-upx.py"
            set /p content=<url
            echo CONTENT=%content% >> %GITHUB_ENV%
            curl -L -o upx.zip %content%
            mkdir upx
            tar -xf "upx.zip" -C upx --strip-components=1
      - name: Build with pyinstaller
        run: |
            pyinstaller --onefile --upx-dir="upx" "Quick Python File Creater.py" --strip

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: Python - Quick Python File Creater
          path: |
            dist/Quick Python File Creater.exe